name: Staging

on:
  push:
    branches:
      - staging
  pull_request:
    branches:
      - staging
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H "${{ secrets.SSH_HOST }}" >> ~/.ssh/known_hosts

      - name: Deploy to server
        run: |
          ssh -T -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} <<-EOF
            eval `ssh-agent -s`
            ssh-add ~/.ssh/${{ secrets.SSH_ID_RSA_NAME}}
            if [ ! -d "/home/${{ secrets.SSH_USER }}/${{ secrets.SERVER_APP_FOLDER }}" ]; then
              mkdir /home/${{ secrets.SSH_USER }}/${{ secrets.SERVER_APP_FOLDER }}
              chown ${{ secrets.SSH_USER }}:${{ secrets.SSH_USER }} /home/${{ secrets.SSH_USER }}/${{ secrets.SERVER_APP_FOLDER }}
              git clone ${{ secrets.SSH_GITHUB_REPOSITORY}} /home/${{ secrets.SSH_USER }}/${{ secrets.SERVER_APP_FOLDER }}
            fi
            cd /home/${{ secrets.SSH_USER }}/${{ secrets.SERVER_APP_FOLDER }}
            git checkout -f staging
            git pull origin staging

            export VITE_API_BASE_URL='${{ secrets.VITE_API_BASE_URL }}'
            export VITE_WEBSOCKET_BASE_URL='${{ secrets.VITE_WEBSOCKET_BASE_URL }}'

            echo "
            VITE_API_BASE_URL='${{ secrets.VITE_API_BASE_URL }}'
            VITE_WEBSOCKET_BASE_URL='${{ secrets.VITE_WEBSOCKET_BASE_URL }}'
            " > /home/${{ secrets.SSH_USER }}/${{ secrets.SERVER_APP_FOLDER }}/.env
            pnpm install
            pnpm run build

          EOF